### ISSUE TITLE
Unit testing coverage 

### ISSUE THREAD

**Issue by briandrawert** [StochSS/GillesPy2#39]

**Comment by georgemhall** [comment]
testing_branch has the latest tests of the model. I branched it off of documentation. 

you can execute run_tests.py and it will discover all tests in the project (ones that match the unittest criteria) and run them. there were some issues with a couple of the tests because of compiler errors on the test for the C solver.

also, there are 2 failing tests in test_simple_model because the error messages will eventually need to be based on the model_sanitization branch. that's an easy fix once we merge documentation and model_sanitization together.
