### ISSUE TITLE
Error when pickling models with lambda expressions

### ISSUE THREAD

**Issue by BryanRumsey** [StochSS/GillesPy2#506]
This occurs when models contain function definitions

## Traceback
```
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-7-7718b618fc93> in <module>
      1 import pickle
----> 2 p_res = pickle.dumps(results)

PicklingError: Can't pickle <function <lambda> at 0x7f179ab14ee0>: attribute lookup <lambda> on math failed
```

**Comment by briandrawert** [comment]
Please add tests to CI system (@BryanRumsey 's test model)

**Comment by ethangreen-dev** [comment]
Python lambdas are not able to be pickled via `pickle` because objects of type `FunctionType` are not supported. Libraries like `dill` support lambdas because they override the default `pickle` implementation. 

Unless we want to get deep into writing our own serializer and deserialize we should probably investigate libraries like `dill` and `cloudpickle`.
