### ISSUE TITLE
Error invoking defined parameters with Gillespy2  Polymerization model

### ISSUE THREAD

**Issue by teddiclax** [StochSS/GillesPy2#634]
Good day.
Based on a previous issue( #537) that involves the use of the Gillespie algorithm to simulate the stochastic trajectory of the polymerization of styrene in free radicals.
How do I invoke any of the initially defined species and manipulate them mathematically to obtain some specific graphs? (In my case for polymerization, the monomer is depleting and the polymer is increasing with time) .
(1)
M0=104;
X= (M0-M)/M0    upon which the resulting "X" will be plotted against the 'Time'.
I get the following error:
'TypeError: unsupported operand type(s) for -: 'float'' OR 'ValueError: unsupported operand type(s) for -: 'str() or int()
(2)
D=104;
Mw=sum(int(f"D{n}"))   upon which the resulting "Mw" will be plotted against the time.
I get the following error:
'TypeError: unsupported operand type(s) for -: 'float'' OR 'ValueError: unsupported operand type(s) for -: 'str() or int().

I have tried correcting the error by applying 'int()' or 'float()'.Please, can you suggest a way or ways to solve this?
Looking forward to your quick response. Thank you.

**Comment by ethangreen-dev** [comment]
Hey @teddiclax. I'm unsure of what you're specifically asking for, but I recommend looking through the `Results` class documentation [here](https://stochss.github.io/GillesPy2/classes/gillespy2.core.html#gillespy2.core.results.Results). Note the plotting-specific functions as they might fulfill your visualization requirement. Use `to_array()` if you need raw simulation results (`numpy.ndarray`), but additional post-processing may be necessary. 

I recommend perusing through [this doc page](https://stochss.github.io/GillesPy2/getting_started/basic_usage/basic_usage.html) and [this notebook](https://github.com/StochSS/GillesPy2/blob/main/examples/ResultsManagement/basic-results-management.ipynb) for `Results` object manipulation and plotting.

As far as your errors, it looks like the first one is caused by `X = (M0 - M) / M0` -- `M` isn't a numeric type. The second seems to be the same issue (based on the error message), but `Mw = sum(int(f"D{n}"))` will throw an exception as you cannot convert any `f"D{n}"` to an integer.
