### ISSUE TITLE
model hashes don't match for Solver.Model and model passed to Solver.run

### ISSUE THREAD

**Issue by BryanRumsey** [StochSS/GillesPy2#677]
[Devils DFTD 2-Stage Infection with Vaccination.ipynb](https://github.com/StochSS/devils_dftd_modeling/blob/param-sweeps/Parameter%20Sweeps/Devils%20DFTD%202-Stage%20Infection%20with%20Vaccination.ipynb)
[json version](https://gist.github.com/BryanRumsey/8a05bed3b68e18e661aaffec16a9240a#file-hash-error-example)

**Comment by ethangreen-dev** [comment]
This problem is caused by `Simulation#configure` in your notebook. `model` is created and passed directly into the solver instance:

``` python
def configure(self):
  solver = TauHybridCSolver(model=model, variable=True)
  self.kwargs = {
      "solver": solver,
      "number_of_trajectories": 1,
  }
```

However, later code adds a new property to this model:

``` python
# Configure Infection Period
run_args['variables']['Infected'] = "1"
run_args['variables']['Susceptible'] = f"{int(res1[0]['Susceptible'][-1] - 1)}"
if 'vaccine_time' in run_args['variables']:
    vaccine_time = run_args['variables']['vaccine_time']
else:
    vaccine_time = self.model.listOfParameters['vaccine_time'].value
``` 

Which sets `model.vaccine_time` to `0.0`. Since `vaccine_time` is in model but not `solver.model`, the following validation in `TauHybridCSolver#run` fails:

``` python
if model is not None and model.get_json_hash() != self.model.get_json_hash():
    raise SimulationError("Model must equal TauHybridCSolver.model.")
```

Note this diff -- `self.model` is on the left, the incoming model is on the right:
![image](https://user-images.githubusercontent.com/70916930/149718545-f503aca7-9408-43ed-bd1e-f33648339b38.png)


I was able to fix this issue with the following change:

``` python
def configure(self):
  solver = TauHybridCSolver(model=None, variable=True)
  self.kwargs = {
      "solver": solver,
      "number_of_trajectories": 1,
  }
```
