### ISSUE TITLE
Slow SSA simulation time for large-isg model

### ISSUE THREAD

**Issue by TorkelE** [StochSS/GillesPy2#724]
I have a model (attached in .txt file, actually an SBML .XML file, but can't upload that to GitHub, so changed the extension). When I try an SSA simulation of the model, it takes surprisingly long time (here I use t=10, which is doable, but if I go towards t= 100 or 1000, the times get _very_ long. Am I doing something wrong?
```python
import sys, os, numpy, libsbml, gillespy2
import numpy
from gillespy2 import NumPySSASolver, SSACSolver

model_egfr_net = gillespy2.core.import_SBML('egfr_net.txt')[0]

%time red = model_egfr_net.run(t=10.0)
```
(somewhere 3-4 minutes run time)

I also try using `SSACSolver`:
```python
%time red = model_egfr_net.run(solver=SSACSolver, t=10.0)
```
but I get output:
```
2022-02-16 17:10:07,756 - root - WARNING - Please install/configure 'g++' and 'make' on your system, to ensure that GillesPy2 C solvers will run properly.
2022-02-16 17:10:07,756 - root - WARNING - Please install/configure 'g++' and 'make' on your system, to ensure that GillesPy2 C solvers will run properly.
---------------------------------------------------------------------------
ModelError                                Traceback (most recent call last)
~/.local/lib/python3.7/site-packages/gillespy2/core/model.py in run(self, solver, timeout, t, increment, show_labels, cpp_support, algorithm, **solver_args)
    987         try:
--> 988             return solver.run(model=self, t=t, increment=increment, timeout=timeout, **solver_args)
    989         except Exception as e:

~/.local/lib/python3.7/site-packages/gillespy2/solvers/cpp/ssa_c_solver.py in run(self, model, t, number_of_trajectories, timeout, increment, seed, debug, profile, variables, resume, live_output, live_output_options, **kwargs)
     62             "Events": len(self.model.listOfEvents),
---> 63             "Function Definitions": len(self.model.listOfFunctionDefinitions)
     64         })

~/.local/lib/python3.7/site-packages/gillespy2/solvers/cpp/c_solver.py in _validate_sbml_features(self, unsupported_features)
    374         if len(detected):
--> 375             raise gillespyError.ModelError(f"Could not run Model.  SBML Feature: {detected} not supported by SSACSolver.")
    376 

ModelError: Could not run Model.  SBML Feature: ['Assignment Rules'] not supported by SSACSolver.

During handling of the above exception, another exception occurred:

SimulationError                           Traceback (most recent call last)
<timed exec> in <module>

~/.local/lib/python3.7/site-packages/gillespy2/core/model.py in run(self, solver, timeout, t, increment, show_labels, cpp_support, algorithm, **solver_args)
    998                                 " run properly.")
    999             raise SimulationError(
-> 1000                 "argument 'solver={}' to run() failed.  Reason Given: {}".format(solver, e))
   1001 
   1002 

SimulationError: argument 'solver=<class 'gillespy2.solvers.cpp.ssa_c_solver.SSACSolver'>' to run() failed.  Reason Given: Could not run Model.  SBML Feature: ['Assignment Rules'] not supported by SSACSolver.
```
I thought I managed to install g++ and make, but not sure how to configure them. In either case, the 'Assignment Rules' seems to mess it up (so maybe g++ and make are ok?)

[egfr_net.txt](https://github.com/StochSS/GillesPy2/files/8081900/egfr_net.txt)

**Comment by briandrawert** [comment]
This is expected behavior, and is a classic example of the trade-off between performance and features.  The `SSACSolver` is a C++ implementation of the Gillespie algorithm exactly, and is designed for performance.  If a user wants to use additional features in their model, such as the Assignment Rule, then we provide the `TauHybridSolver`. This solver is written in Python and implements a very large feature set.  Of course, a Python solver will not be as efficient as a C++ solver.  Implementing additional features in the `SSACSolver`  will significantly degrade its performance.  Our current development is centered around the `TauHybridCSolver`, a C++ implementation that will increase simulation performance for these models.

Please note that in this case, the message: 
`2022-02-16 17:10:07,756 - root - WARNING - Please install/configure 'g++' and 'make' on your system, to ensure that GillesPy2 C solvers will run properly.` is being shown erroneously.  I have made an issue to address this #725.

**Comment by briandrawert** [comment]
Also, please note that you are not running an "SSA simulation" (i.e. discrete species populations) for your model, as the SBML model does not specify that the species should be discrete.  They are explicitly set at continuous in your SBML.

**Comment by briandrawert** [comment]
The most efficient way to accomplish your goal is to remove the Assignment rules from the simulation, since they is no reason to calculate them "during" the simulation.  It is more efficient to calculate them later, as a post-processing.

An example of how to do that is shown here: https://live.stochss.org/stochss/present-notebook?owner=bdrawert_40unca_2Eedu&file=c225588f2eb8f496066dafc7b7e4b281.ipynb
